# Generated by Django 2.2.6 on 2019-12-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='Month',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monthlysaving',
            name='Month',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Employee')),
            ],
        ),
    ]
