# Generated by Django 3.0 on 2019-12-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_employee_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Email',
        ),
    ]
