# Generated by Django 3.0 on 2019-12-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Postion',
        ),
    ]
